name: Translation Pipeline

on: push

jobs:
  translation-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate and commit translations
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 1. Generate JSON
          echo "Running conversion script..."
          node cypress/fixtures/convertExcel.js
          
          # 2. Verify output
          echo "Generated files:"
          ls -la cypress/fixtures/
          
          if [ ! -f "cypress/fixtures/full_translation.json" ]; then
            echo "::error::Failed to generate full_translation.json"
            exit 1
          fi
          
          # 3. Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add cypress/fixtures/full_translation.json
          git commit -m "Auto-generated translation JSON [skip ci]"
          git push "https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git"

      - name: Process language code
        id: language
        run: |
          # Get the commit that triggered the workflow
          TRIGGER_MSG="${{ github.event.head_commit.message }}"
          echo "Analyzing triggering commit: $TRIGGER_MSG"
            
          # Extract language code (format: [xx-xx])
          LANGUAGE_CODE=$(echo "$TRIGGER_MSG" | grep -oE '\[[a-z]{2}-[a-z]{2}\]' | head -1 | tr -d '[]')
            
          # Validate extraction
          if [[ ! $LANGUAGE_CODE =~ ^[a-z]{2}-[a-z]{2}$ ]]; then
            echo "::error::Commit message must contain [lang-code] format (e.g., [pt-br])"
            echo "Triggering commit was: $TRIGGER_MSG"
            exit 1
          fi
            
          echo "Using language code: $LANGUAGE_CODE"
          echo "language_code=$LANGUAGE_CODE" >> $GITHUB_OUTPUT

      - name: Rename test file for extracted language code
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Current test files:"
          ls -la cypress/e2e/
          
          # Find and rename the test file (using hyphen instead of brackets)
          OLD_FILE=$(find cypress/e2e -name 'translation*.cy.js' | head -1)
          if [ -z "$OLD_FILE" ]; then
            echo "::error::No translation test file found in cypress/e2e/"
            exit 1
          fi
          
          NEW_FILE="cypress/e2e/translation-${LANGUAGE_CODE}.cy.js"
          echo "Renaming $OLD_FILE to $NEW_FILE"
          mv -f "$OLD_FILE" "$NEW_FILE"
          
          # Commit the renamed file
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "$NEW_FILE"
          git commit -m "Renamed test file for ${LANGUAGE_CODE} [skip ci]"
          git push "https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git"

      - name: Verify test file exists
        run: |
          TEST_FILE="cypress/e2e/translation-${LANGUAGE_CODE}.cy.js"
          if [ ! -f "$TEST_FILE" ]; then
            echo "::error::Test file not found: $TEST_FILE"
            ls -la cypress/e2e/
            exit 1
          fi
          echo "Found test file: $TEST_FILE"

      - name: Run translation tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          spec: "cypress/e2e/translation-${LANGUAGE_CODE}.cy.js"
          config-file: cypress.config.js

      - name: Generate HTML report
        if: always()
        run: |
          npx mochawesome-merge cypress/reports/mocha/*.json > merged-report.json
          npx marge merged-report.json --reportDir cypress/reports/html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: translation-report-${{ steps.language.outputs.language_code }}
          path: cypress/reports/html/merged-report.html